name: Validate PR Checkboxes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  checkbox-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Checkbox Groups
        uses: ./.github/actions/checkboxvalidator
